"""create_followers_table

Revision ID: 059bf0c3a92b
Revises: aa617fade1f3
Create Date: 2019-08-28 20:27:02.612003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059bf0c3a92b'
down_revision = 'aa617fade1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
